version: '3'

services:
  runner.workerconsole:
    image: runner.workerconsole
    build:
      context: .
      dockerfile: ../Runner.WorkerConsole/Dockerfile
    environment:
      - modules__2__properties__OutputPath=/templates/output
      - modules__2__properties__ZipDeliveryPath=/templates/zip
      - modules__2__properties__StorageAccountName=orders2caju
      - modules__2__properties__AccessKey=D949P99wWM8i4cttbdUDJv5zNbI/In7OJpBgen8lTO/8rk5ov43WnuPTV/EBWEgXnAS+4VwfNNZaapST0zYVMg==
      - modules__3__properties__BrokerList=10.0.75.1:9092
      - modules__3__properties__Topic=template-orders-02